spring.application.name=financial-manager

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=3

management.endpoints.web.exposure.include=health
